# Site settings
title: JaceMakes 
email:jacemakes@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "https://indiecolorgrading.com/jacemakes.github.io/" 
url: "https://indiecolorgrading.com/" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
